CREATE TABLE hostelboys (
 ID INTEGER PRIMARY KEY,
 NAME TEXT,
 AGE INTEGER,
 SEX TEXT,
 CLASS TEXT,
 NICKNAME TEXT
);

INSERT INTO hostelboys VALUES 
(1,"ABIOLA FAWAS",10,"MALE","SSS1A6","FASCO"),
(2,"OBADIMU TESLIM",19,"MALE","SSS1A2","TESLA "),
(3,"ASSANI ABDULRASAQ",2,"MALE","SSS1A1","FOOL OF THE SCHOOL "),
(4,"AJIBIKE ABDUL AZEEZ ",1,"MALE","SSS1A2","PAKO "),
(5,"OBADIMU TESLIM",19,"MALE","SSS1A2","BEST "),
(6,"ISMAILIMRAN",19,"MALE","SSS1A2","IIB "),
(7,"AKINDE AZEEM",1,"MALE","SSS1A9","ODE "),
(8,"AWOGWU CHUKA",0.1,"MALE","SSS1A0.000","FOLLISH FOOL ");

SELECT * FROM hostelboys;


SELECT * FROM hostelboys WHERE NICKNAME = "ODE" ;

